spring.application.name=chpater02

server.port=8081

# open AI
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.model=gpt-5-mini
spring.ai.openai.chat.temperature=1.0

# ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3:latest

logging.level.org.springframework.ai.chat.client.advisor=DEBUG